services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "ltsc10"
      LANGUAGE: "Italian"
      REGION: "it-IT"
      KEYBOARD: "it-IT"
      DISK_SIZE: "26G"
      RAM_SIZE: "7G"
      CPU_CORES: "4"
      USERNAME: "Windows"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
